version: '3.6'

services:
  server:
    image: nginx:alpine
    restart: always
    volumes:
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports: 
      - "127.0.0.1:8000:80"
    networks:
      - invoiceninja

  app:
    image: invoiceninja/invoiceninja:latest
    restart: always
    environment: 
      - APP_URL=http://server
      - APP_KEY=QbGTQrFDvWM7TZEBXTt9YCVJDpzqh6Kk
      - DB_HOST=db
    volumes:
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - db
    networks: 
      - invoiceninja  

  db:
    image: mariadb:latest
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=QrbcAzYVGwZcWArqt4sLAcXGE3qGCCzu
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=ninja
      - MYSQL_DATABASE=ninja
    volumes:
      # - mysql-data:/var/lib/mysql:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./mysql_data:/var/lib/mysql:rw,delegated
    networks:
      - invoiceninja

 
  # cron:
  #   image: invoiceninja/invoiceninja
  #   volumes:
  #     -  storage:/var/www/app/storage
  #     -  logo:/var/www/app/public/logo
  #     -  public:/var/www/app/public
  #   entrypoint: |
  #     bash -c 'bash -s <<EOF
  #     trap "break;exit" SIGHUP SIGINT SIGTERM
  #     sleep 300s
  #     while /bin/true; do
  #       ./artisan ninja:send-invoices
  #       ./artisan ninja:send-reminders
  #       sleep 1d
  #     done
  #     EOF'
  #   networks:
  #     - invoiceninja

volumes:
  mysql-data:
  public:
  storage:

networks:
  invoiceninja:
